services:
  app:
    build: .
    container_name: my-nodejs-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm start
